<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'Aktiv',
    'Alias' => 'Alias',
    'An error occured. Please try again.' => 'Der skete en fejl. Prøv venligst igen.',
    'Available blocks' => 'Mulige blokke',
    'Block' => 'Blok',
    'Choose a menu for this item' => '',
    'Content' => 'Indhold',
    'Direction can only be "up" or "down"' => 'Retning kan kun være "op" eller "ned"',
    'Extension' => 'Udvidelse',
    'Inactive' => 'Inaktiv',
    'Is default' => 'Er standard',
    'Media' => 'Medie',
    'Menu' => 'Menu',
    'Menu item moved down.' => 'Menupunkt flyttet ned',
    'Menu item moved up.' => 'Menupunkt flyttet op',
    'Menu item not moved. It is the first item.' => 'Menupunkt ikke flyttet. Det er første punkt.',
    'Menu item not moved. It is the last item.' => 'Menupunkt ikke flyttet. Det er sidste punkt.',
    'Menus' => 'Menuer',
    'Meta description' => 'Meta beskrivelse',
    'Meta keywords' => 'Meta nøgleord',
    'Meta title' => 'Meta titel',
    'Name' => 'Navn',
    'Namespace' => 'Klasse',
    'No' => 'Nr',
    'Parent' => 'Læg under',
    'Positions' => 'Positioner',
    'Route' => 'Url',
    'Scope' => 'Anvendelse',
    'Section' => 'Sektion',
    'Select a link' => 'Vælg et link',
    'Select media' => 'Vælg medie',
    'Select section' => 'Vælg sektion',
    'Show title' => 'Vis titel',
    'State' => 'Status',
    'Thrashed' => 'Smidt ud',
    'Title' => 'Titel',
    'Type' => 'Type',
    'Yes' => 'Ja',
];
